### ISSUE TITLE
Video Url in not found . Download function is not woking. I share log 

### ISSUE THREAD

**Issue by asp3443** [UmairOye/TIKTOK-VIDEO-DOWNLOADER-WITHOUT-WATERMARK#1]
Video url -> is https://www.tiktok.com/notfound
 Video id  is -> null

**Comment by UmairOye** [comment]
> Video url -> is https://www.tiktok.com/notfound Video id is -> null

Hi @asp3443, hope you are doing well, if you want to download any video from tiktok using this tool/app, you have to copy link directly from tiktok app, not from web or any other third party app so it will work fine.

currently am using regix to get video id and based on it i am able to download that video.
